name: linux-x86-cpu-gcc
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  linux-gcc:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./scripts/build_linux_naive.sh
